version: '3'

services:
  db:
    image: postgres:15.5-alpine
    ports:
      - 5432:5432
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app

  pgadmin:
    image: dpage/pgadmin4:7.6
    ports:
      - 9000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    depends_on:
      - db
